#application port
server:
  port: 8595

#application configuration
spring:
  application:
    name: price-engine
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/price-engine?createDatabaseIfNotExist=false
    username: root
    password: 1221
    #platform: platform: org.hibernate.dialect.MySQL5Dialect
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: create







